eureka:
  client:
    service-url:
      defaultZone: http://10.148.0.8:9001/eureka, http://10.148.0.7:9001/eureka, http://10.148.0.9:9001/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.smartclinic: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
