server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/appointment_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
