spring:
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointments/**
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/billings/**
#      globalcors:
#        add-to-simple-url-handler-mapping: true
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins:
#              - "http://localhost:5173"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            allowedHeaders: "*"
#            allowCredentials: true

server:
  port: 7000
